apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    run: nginx-green
  type: NodePort
  ports:
    - name: nginx-green-port
      nodePort: 32458
      port: 8080
      targetPort: 80